global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'core-server-app' # <--- ИЗМЕНЕНИЕ: Имя сервиса
    metrics_path: /metrics
    static_configs:
      - targets: ['core-server-app:3000'] # <--- ИЗМЕНЕНИЕ: Имя сервиса

  - job_name: 'auth-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-service:3001']